server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info